#!/usr/bin/env python3
import sys
import os

# Add the project root directory to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ftpserver.core.server import FTPServer

if __name__ == "__main__":
    server = FTPServer(host="0.0.0.0", port=2121)
    server.start()